version: '3'
services:
  mongo:
    image: mongo:3.4  
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27021:27017"
    command: mongod --auth
    restart: always
  web:
    depends_on:
      - mongo
    build: .
    ports:
      - "3001:3000"
    links:
      - mongo
    restart: always
